
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADRIAN WIN
 */
public class AplikasiPenghitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitunganHari
     */
    public AplikasiPenghitunganHari() {
        initComponents();
        // Membuat model untuk spinnerTahun dengan nilai awal 2024, batas minimum 1900, batas maksimum 2100, dan langkah 1
        SpinnerNumberModel tahunModel = new SpinnerNumberModel(2024, 1900, 2100, 1);

        // Menetapkan model spinner untuk komponen spinnerTahun
        spinnerTahun.setModel(tahunModel);
    }
    // Metode untuk menerjemahkan nama hari dari bahasa Inggris ke bahasa Indonesia
    private String terjemahHari(java.time.DayOfWeek hari) {
        // Menggunakan switch case standar untuk kompatibilitas dengan NetBeans 8.2
        switch (hari) {
            case MONDAY:
                return "Senin";
            case TUESDAY:
                return "Selasa";
            case WEDNESDAY:
                return "Rabu";
            case THURSDAY:
                return "Kamis";
            case FRIDAY:
                return "Jumat";
            case SATURDAY:
                return "Sabtu";
            case SUNDAY:
                return "Minggu";
            default:
                return "";
        }
    }

    // Metode untuk memperbarui JComboBox dan JSpinner sesuai dengan tanggal yang dipilih pada JCalendar
    private void sinkronkanComboBoxDanSpinner() {
        java.util.Calendar cal = calenderPilihTgl.getCalendar();
        if (cal != null) {
            int bulan = cal.get(java.util.Calendar.MONTH);
            int tahun = cal.get(java.util.Calendar.YEAR);
            cmbBulan.setSelectedIndex(bulan);
            spinnerTahun.setValue(tahun);
        }
    }

    // Metode untuk memperbarui tanggal pada JCalendar berdasarkan pilihan bulan dan tahun
    private void perbaruiKalender() {
        int bulanDipilih = cmbBulan.getSelectedIndex();
        int tahunDipilih = (int) spinnerTahun.getValue();
        java.util.Calendar kalender = java.util.Calendar.getInstance();
        kalender.set(java.util.Calendar.YEAR, tahunDipilih);
        kalender.set(java.util.Calendar.MONTH, bulanDipilih);
        kalender.set(java.util.Calendar.DAY_OF_MONTH, 1);
        calenderPilihTgl.setDate(kalender.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cmbBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        lblBulan = new javax.swing.JLabel();
        spinnerTahun = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        lblPilihTgl = new javax.swing.JLabel();
        calenderPilihTgl = new com.toedter.calendar.JCalendar();
        jPanel3 = new javax.swing.JPanel();
        btnSelisih = new javax.swing.JButton();
        lblSelisih = new javax.swing.JLabel();
        lblTglAwal = new javax.swing.JLabel();
        lblTglAkhir = new javax.swing.JLabel();
        calenderTglAwal = new com.toedter.calendar.JCalendar();
        calenderTglAkihr = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penghitungan Hari");

        jPanel4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Penghitungan Hari", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Roboto", 1, 24), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cmbBulan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBulanItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(cmbBulan, gridBagConstraints);

        lblTahun.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTahun.setText("Masukkan Tahun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(lblTahun, gridBagConstraints);

        lblBulan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblBulan.setText("Pilih Bulan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(lblBulan, gridBagConstraints);

        spinnerTahun.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        spinnerTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerTahunStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(spinnerTahun, gridBagConstraints);

        jPanel4.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perhitungan Jumlah Hari", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Roboto", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblHariPertama.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(lblHariPertama, gridBagConstraints);

        lblHariTerakhir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(lblHariTerakhir, gridBagConstraints);

        btnHitung.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnHitung.setText("Hitung Jumlah Hari");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(btnHitung, gridBagConstraints);

        lblPilihTgl.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblPilihTgl.setText("Pilih Tanggal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(lblPilihTgl, gridBagConstraints);

        calenderPilihTgl.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        calenderPilihTgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calenderPilihTglPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(calenderPilihTgl, gridBagConstraints);

        jPanel4.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hitung Selisih Hari", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Roboto", 1, 14))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnSelisih.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnSelisih.setText("Hitung Selisih Hari");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(btnSelisih, gridBagConstraints);

        lblSelisih.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(lblSelisih, gridBagConstraints);

        lblTglAwal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTglAwal.setText("Tanggal Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(lblTglAwal, gridBagConstraints);

        lblTglAkhir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTglAkhir.setText("Tanggal Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(lblTglAkhir, gridBagConstraints);

        calenderTglAwal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(calenderTglAwal, gridBagConstraints);

        calenderTglAkihr.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(calenderTglAkihr, gridBagConstraints);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerTahunStateChanged
        perbaruiKalender();
    }//GEN-LAST:event_spinnerTahunStateChanged

    private void cmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBulanItemStateChanged
        perbaruiKalender();
    }//GEN-LAST:event_cmbBulanItemStateChanged

    private void calenderPilihTglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calenderPilihTglPropertyChange
        sinkronkanComboBoxDanSpinner();
    }//GEN-LAST:event_calenderPilihTglPropertyChange

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // Metode untuk menghitung jumlah hari dalam bulan yang dipilih
        String namaBulan = cmbBulan.getSelectedItem().toString();
        int tahun = (int) spinnerTahun.getValue();
        int indexBulan = cmbBulan.getSelectedIndex() + 1;

        java.time.YearMonth ym = java.time.YearMonth.of(tahun, indexBulan);
        int hariDalamBulan = ym.lengthOfMonth();

        java.time.LocalDate hariPertama = ym.atDay(1);
        java.time.LocalDate hariTerakhir = ym.atEndOfMonth();

        boolean kabisat = java.time.Year.isLeap(tahun);
        String pesanKabisat = kabisat ? " (Tahun Kabisat)" : "";

        String hariAwal = terjemahHari(hariPertama.getDayOfWeek());
        String hariAkhir = terjemahHari(hariTerakhir.getDayOfWeek());

        String hasil = String.format(
                "Jumlah Hari: %d%s\nHari Pertama: %s\nHari Terakhir: %s",
                hariDalamBulan, pesanKabisat, hariAwal, hariAkhir
        );
        JOptionPane.showMessageDialog(this, hasil);

        lblHariPertama.setText("Hari Pertama: " + hariAwal);
        lblHariTerakhir.setText("Hari Terakhir: " + hariAkhir);

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        java.util.Date tglMulai = calenderTglAwal.getDate();
        java.util.Date tglAkhir = calenderTglAkihr.getDate();

        if (tglMulai != null && tglAkhir != null) {
            java.time.LocalDate mulai = tglMulai.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            java.time.LocalDate akhir = tglAkhir.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            long selisih = java.time.temporal.ChronoUnit.DAYS.between(mulai, akhir);
            String hasilSelisih = "Selisih Hari: " + Math.abs(selisih) + " hari";

            lblSelisih.setText(hasilSelisih);
            JOptionPane.showMessageDialog(this, hasilSelisih);
        } else {
            JOptionPane.showMessageDialog(this, "Tanggal Belum Lengkap Dipilih.", "Kesalahan Input!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSelisihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSelisih;
    private com.toedter.calendar.JCalendar calenderPilihTgl;
    private com.toedter.calendar.JCalendar calenderTglAkihr;
    private com.toedter.calendar.JCalendar calenderTglAwal;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblPilihTgl;
    private javax.swing.JLabel lblSelisih;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTglAkhir;
    private javax.swing.JLabel lblTglAwal;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
